### ISSUE TITLE
How to install this on Google colab?

### ISSUE THREAD

**Issue by QAQOAO** [bearpelican/musicautobot#11]
Hi, I tried installing this package with 

    !git clone https://github.com/bearpelican/musicautobot.git

    cd musicautobot

    !wget https://repo.anaconda.com/archive/Anaconda3-5.2.0-Linux-x86_64.sh && bash Anaconda3-5.2.0-Linux-x86_64.sh -bfp /usr/local

    import sys
    sys.path.append('/usr/local/lib/python3.6/site-packages')

    !conda env update -f environment.yml

    !sudo apt-get install musescore

    !source activate musicautobot

on colab, and run

    %reload_ext autoreload
    %autoreload 2
    %matplotlib inline
 
    import os
    os.chdir('../../')

everything is fine, but importing musicautobot got me an error

    from musicautobot.numpy_encode import *
    from musicautobot.config import *
    from musicautobot.music_transformer import *
    from musicautobot.utils.midifile import *
    from musicautobot.utils.file_processing import process_all

File "/content/musicautobot/musicautobot/music_transformer/transform.py", line 1
    from __future__ import annotations
                                      ^
SyntaxError: future feature annotations is not defined

**Comment by bearpelican** [comment]
Looks like future is only supported in python 3.7.

0a057446507f3520e68df33f7c7ca0d9719954c3 should fix support for 3.6
