### ISSUE TITLE
An example of training directly from .txt files?

### ISSUE THREAD

**Issue by jbmaxwell** [bearpelican/musicautobot#14]
I'm wondering if there's an example of training from .txt files? I have my own representation, from which I'm generating .txt files from MIDI. I just need a bit of guidance on how I'd go about formatting these for the multitask transformer.

Any advice appreciated!

**Comment by bearpelican** [comment]
Currently don't have an example training from .txt files. I'd like to add this eventually.

I previously had code doing that, but deprecated it for performance issues. Here's the relevant bits:
https://github.com/bearpelican/musicautobot/blob/86b5ced94a1140fa8a62e45118fec94cbf38003e/src/v1/fastai_data.py
https://github.com/bearpelican/musicautobot/blob/86b5ced94a1140fa8a62e45118fec94cbf38003e/notebooks/text_encoding/ulmfit/ULMFit-1-notebook_train.ipynb

As long as you are able to tokenize your txt files, it should work.
Note that the MultitaskTransformer requires you to separate the chords and melody. MusicTransformer does not.
