### ISSUE TITLE
Question about triplets, beat resolution, vocabulary size

### ISSUE THREAD

**Issue by xhevahir** [bearpelican/musicautobot#15]
I was wondering about the possibility of triplets. Musicautobot has a default beat grid of 16 steps in a 4/4 measure, or 4 pulses per quarter note. In order to encode eighth-note triplets (probably the shortest duration of triplet that would be useful), the beat grid would need to be 96 PPQN, i.e. 24 times as fine a resolution. Is that worth attempting, or would the much larger number of durations require too large a vocabulary?

**Comment by bearpelican** [comment]
I think that's totally fine. My duration vocab size is 160. Multiplying that by 24 is still pretty reasonable - compared to language model vocab sizes
