### ISSUE TITLE
Does prediction with the pre-trained model use GPU?

### ISSUE THREAD

**Issue by xhevahir** [bearpelican/musicautobot#16]
I don't have a GPU and can't figure out whether any of the prediction (not training) tasks use a GPU, or only the CPU. Would running it on a GPU speed things up considerably?

**Comment by bearpelican** [comment]
Predictions uses the GPU if there is one available. 

Not sure the exact speedup, but you can try running the code on a GPU with colab - https://colab.research.google.com/github/bearpelican/musicautobot/blob/master/notebooks/multitask_transformer/Generate_colab.ipynb
