### ISSUE TITLE
RunTimeError & ValueError 

### ISSUE THREAD

**Issue by QAQOAO** [bearpelican/musicautobot#17]
I got the same RunTimeError when I tried to execute learn.predict in both "Generate" and "Train" ipynb.  All of the cells above the "predict" cells worked just fine. Besides, I got ValueError in "Train-Simple" ipynb. All of the cells above the "learn.fit_one_cycle(4)" cells worked just fine. I wonder is it only me that encountered these problems.

In /notebooks/music_transformer/Generate.ipynb

pred, full = learn.predict(seed_item, n_words=400, temperatures=(1.1,0.4), min_bars=12, top_k=24, top_p=0.7)

RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.cuda.IntTensor instead (while checking arguments for embedding)

In /notebooks/music_transformer/Train.ipynb

pred, full = learn.predict(item, n_words=100)

RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.cuda.IntTensor instead (while checking arguments for embedding)

In /notebooks/music_transformer/Train-Simple.ipynb

learn.fit_one_cycle(4)

ValueError: too many values to unpack (expected 2)

**Comment by bearpelican** [comment]
Hmm that error usually happens when the model encounters a token index that is larger than the embedding size.

Can you check the maximum value of your input sequence?
`seed_item.data.max()`
It should be less than the vocab size:
`len(vocab`

**Comment by QAQOAO** [comment]
Well, I just checked that out and found that it was fine. 

seed_item.data.max() = 161, len(vocab) = 312

Also, I just used your midi files in 'data/midi/examples' and tried to reproduce your results.

So, I think that error is caused by other issues.

**Comment by bearpelican** [comment]
Are you using windows? If so, it could be [related](https://www.gitmemory.com/issue/nikitakit/self-attentive-parser/25/498689123)

Could you try pulling the latest master and try again? 8ad147115a57ffcdbe539ddef62854593e87d913 should fix it

**Comment by QAQOAO** [comment]
Yeah, by changing return t to return t.long() solves RuntimeError.

I really appreciate your reply!

But there is still one more issue, can you also help ValueError in Train-Simple.ipynb?

In /notebooks/music_transformer/Train-Simple.ipynb

learn.fit_one_cycle(4)

ValueError: too many values to unpack (expected 2)

**Comment by bearpelican** [comment]
135807373ec6a750faac56bd513fd79b9f74d119 should fix Train-Simple.

Thanks for reporting this!
