### ISSUE TITLE
Error while importing music_transformer

### ISSUE THREAD

**Issue by David-D-Chen** [bearpelican/musicautobot#3]
Hi Andrew, I was running the Midi2Tensor notebook and there was a problem when importing music_transformer. I think the issue came from the append method in transform.py - I haven't tested it, but I think it might be fixed if you add a vocab argument.

Thanks for checking it out!

**Comment by bearpelican** [comment]
Hmm I'm not able to reproduce. Could you paste in the error/stack trace you are seeing?

The vocab argument should be passed in automatically when self.new is called.

**Comment by David-D-Chen** [comment]
Hmm you're right the issue went away when I ran it again today. Bizarre. Thanks anyway!
