### ISSUE TITLE
In "notebooks/music_transformer/train.ipynb", data format mismatch

### ISSUE THREAD

**Issue by cwh0118** [bearpelican/musicautobot#5]
In #Show Data block, when execute 
data.train_dl.on_epoch_begin()
x, y = data.one_batch();
x, y
the output format is like this:
(tensor( [ [ [   0, 0],
                  [  1, 0],
                  [77, 0], ...)
seems like load position info, which is different from the declared output:
(tensor([[  0,   1,  76, 138,  64, 140,  59, 140,  57, 140,   8, 138],
         [139,  75, 139,   8, 139,  73, 141,   8, 141,  70, 138,   8]]),
and lead to learn.fit_one_cycle(4) to crash:
in music_transformer/model.py 
def forward:
   ...
    bs, x_len = x.size() to many value to unpack

how should I fix this bug?
big thx!

**Comment by bearpelican** [comment]
Ah good catch. 2db5a22ddee3a9741c1aea2839d1844e2fa6ecc2 should fix it!
