### ISSUE TITLE
Generating new melody to fit existing chord progression AND melodic rhythm?

### ISSUE THREAD

**Issue by xhevahir** [bearpelican/musicautobot#8]
Hi, I'm trying to use this project do something like what Hooktheory demonstrate in [this video](https://www.hooktheory.com/videos/31), and I'm not sure how to proceed. Basically, I want to take a MIDI file of a melody with an accompanying chord progression, and regenerate the pitches of the melody, while leaving the durations and the chord progression as they are--hopefully using the chord progression as a seed (if that's the right concept) for those new pitches.

Thanks a lot for this repo.

**Comment by bearpelican** [comment]
Interesting problem. The way I would do it is to replace all the melody pitches with the mask token. Then have BERT predict those.

The solution is not as clean solution as I thought it would be, but here's a quick notebook to do so: ttps://github.com/bearpelican/musicautobot/blob/cfeb7330427f37707364a20083f2b5013ee43bd2/notebooks/multitask_transformer/Generate-RemixMelodyPitch.ipynb

Hope that helps!
