### ISSUE TITLE
Excepting Noisy Data?

### ISSUE THREAD

**Issue by Akamight** [bearpelican/musicautobot#9]
When I was trying to use the code provided in the guide on my own dataset (the Reddit one), I ran into a problem：
`music21.midi.MidiException: badly formated midi bytes, got: b'<html>\r\n<head>\r\n<tit'`
which is definitely an error in the midi files because the examples provided in the repository works.

Thus, I'm just curious if there is a way to skip these files - to make the code work even if there are less samples available.

Here is my code:
`midi_path = Path('data/midi/')

# Location to save dataset
data_path = Path('data/numpy')

data_save_name = 'musicitem_data_save.pkl'
midi_files = get_files(midi_path, '.mid', recurse=True)

processors = [Midi2ItemProcessor()]
data = MusicDataBunch.from_files(midi_files, data_path, processors=[Midi2ItemProcessor()], bs=16, bptt=512,
                                 encode_position=True, dl_tfms=[batch_position_tfm])
data.save(data_save_name)`

**Comment by bearpelican** [comment]
I just added a notebook to preprocess the large dataset. This is pretty identical to the code I used to do the same: 2fd9ddba88d94588b231b19ae69cdcdda61c6797

Notebook: https://github.com/bearpelican/musicautobot/blob/master/notebooks/music_transformer/DataPreprocessing-Reddit.ipynb

Hope that helps!
